{{- if .Values.observability.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "docutag.fullname" . }}-grafana
  labels:
    {{- include "docutag.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ include "docutag.storageClass" . }}
  resources:
    requests:
      storage: {{ .Values.observability.grafana.persistence.size }}
{{- end }}
