{{- if .Values.imageRegistry.createPullSecret }}
{{- if and .Values.imageRegistry.username .Values.imageRegistry.password }}
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  labels:
    {{- include "docutag.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.imageRegistry.server .Values.imageRegistry.username .Values.imageRegistry.password (printf "%s:%s" .Values.imageRegistry.username .Values.imageRegistry.password | b64enc) | b64enc }}
{{- end }}
{{- end }}
