{{- if .Values.observability.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "docutag.fullname" . }}-prometheus
  labels:
    {{- include "docutag.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    {{- include "docutag.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
{{- end }}
