{{- if .Values.asynqmon.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "docutag.fullname" . }}-asynqmon
  labels:
    {{- include "docutag.componentLabels" (dict "component" "asynqmon" "type" "monitoring" "context" .) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    {{- include "docutag.componentSelectorLabels" (dict "component" "asynqmon" "context" .) | nindent 4 }}
{{- end }}
